[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_backend"

[project]
name = "market-aggregator"
version = "1.0.0"
description = "Local-first market data aggregator"
requires-python = ">=3.11"
